inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    # Travis installs gems in the vendor directory, which causes rubocop to try
    # and cop our gems. We don't want it to.
    - vendor/**/*
    - 'test/**/*'
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/initializers/secret_token.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/environments/*'
    - 'bin/*'
    - 'config/application.rb'
    - 'config/initializers/content_security_policy.rb'

# The cop is meant to enforce conventions regarding variables containing numbers
# However in 0.43.0 it is bugged. Both changed on master and disabled by default
# The exclusions don't even get added to the rubocop_todo properly!
Naming/VariableNumber:
  Enabled: false
Rails:
  Enabled: true
Rails/FilePath:
  EnforcedStyle: arguments

# Enforces 1234565789 as 123_456_789: While nice when dealing with actual big
# numbers, we're more likely to see it shout at us about barcodes.
Style/NumericLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/*'

Metrics/MethodLength:
  Max: 12
  Exclude:
    - 'db/migrate/*'

Layout/LineLength:
  Max: 100
  Exclude:
    - 'lib/tasks/*'

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Style/ClassAndModuleChildren:
  Enabled: false
