name: Docker CUPS-debian build and publish

on: workflow_dispatch

env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set release name
        run: echo "RELEASE_VERSION=$(printf -- $(cat cups/.cups-release-version))" >> $GITHUB_ENV

      - name: Build the Docker image
        run: >-
          docker build .
          --file Dockerfile
          --tag docker.pkg.github.com/${IMAGE_NAME}:cupsd-${{ env.RELEASE_VERSION }}

      - name: Login to registry
        run: >-
          docker login
          -u ${{ github.actor }}
          -p ${{ secrets.GITHUB_TOKEN }}
          docker.pkg.github.com

      - name: Publish image
        run: >-
          docker push
          docker.pkg.github.com/${IMAGE_NAME}:cupsd-${{ env.RELEASE_VERSION }}